import{S as u,i as l}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&e(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function e(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();function d(s){const n=`https://pixabay.com/api/?key=44095628-d0027d9df3d6429662d87f006&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true`;return console.log("url",n),fetch(n).then(e=>{if(!e.ok)throw new Error("Network response was not ok");return e.json()}).then(e=>e).catch(e=>{throw e})}const f=new u(".gallery a",{captionsData:"alt",captionDelay:300});function m(s){const o=document.querySelector(".gallery");if(o.innerHTML="",s.length===0){iziToast.error({message:"Sorry, there are no images matching your search. Please try again!"});return}const n=s.map(e=>`
                <li class="gallery-item">
                    <a class="gallery-link" href="${e.largeImageURL}">
                        <img src="${e.webformatURL}" alt="${e.tags}">
                    </a>
                    <ul class="item-info">
                        <li class="item-list"><h3>Likes</h3><p>${e.likes}</p></li>
                        <li class="item-list"><h3>Views</h3><p>${e.views}</p></li>
                        <li class="item-list"><h3>Comments</h3><p>${e.comments}</p></li>
                        <li class="item-list"><h3>Downloads</h3><p>${e.downloads}</p></li>
                    </ul>
                </li>
            `).join("");o.innerHTML=n,f.refresh()}const c=document.querySelector(".form"),p=document.querySelector(".input"),a=document.getElementById("loader"),h=document.querySelector(".gallery");a||console.error("Loader element not found");c.addEventListener("submit",function(s){s.preventDefault();const o=p.value.trim();if(o===""){l.error({title:"Error:",message:"Please enter a search term.",position:"topRight"});return}h.innerHTML="",console.log("Showing loader"),a.style.display="block",d(o).then(n=>{const e=n.hits;typeof e=="string"?l.error({title:"Error:",message:e,position:"topRight"}):m(e)}).catch(n=>{l.error({title:"Error:",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}).finally(()=>{console.log("Hiding loader"),a.style.display="none",c.reset()})});
//# sourceMappingURL=commonHelpers.js.map
